cc_library(
    name = "balsaqs",
    srcs = [
        "balsa_queue.cc",
    ],
    hdrs = [
        "balsa_queue.hh",
        "bq_main_macro.hh",
    ],
    deps = [
        "//infrastructure/comms:comm_library",
        "//infrastructure/config",
        "//infrastructure/gonogo",
    ],
    visibility = ["//visibility:public"]
)
