cc_library(
    name = "gonogo",
    srcs = [
        "gonogo.cc",
    ],
    hdrs = [
        "gonogo.hh",
        "gonogo_message.hh",
    ],
    deps = [
        "//infrastructure/comms:comm_library",
    ],
    visibility = ["//visibility:public"],
)
