cc_library(
    name = "engine_messages",
    hdrs = [
        "turbine_state_message.hh",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "schemas",
    srcs = [
        "engine_enums.hh",
    ],
    hdrs = [
        "jetcat_schemas.hh",
    ],
    visibility = ["//visibility:public"],
)
